### PR TITLE
Add setup of gpg key for non flat repo

### PR DESCRIPTION
**Pull request by AymenOtt**
Get url from config , extract key id and download gpg key

### CODE REVIEW

**Review by isbm — CHANGES_REQUESTED** [review]
@AymenOtt the logging facility should reuse `kiwi`'s one, not direct prints to STDOUT. And unit tests should be also added to cover this change.

**Comment by isbm** [comment]
Conflicts

**Comment by isbm** [comment]
> Conflicts

@AymenOtt any updates here?

**Comment by AymenOtt** [comment]
Aborted

**Pull request closed without merging**
