### PR TITLE
replace prints with kiwi.logger

### PR DESCRIPTION
**Pull request by osab270844**
replace prints with kiwi.logger.

### CODE REVIEW

**Review by isbm — CHANGES_REQUESTED** [review]
Tests not passing

**Comment by wintron04** [comment]
You have to change some of the test to capture the correct output. 
However this is already done and completed on PR #41 
I would suggest just closing this PR

**Comment by osab270844** [comment]
@wintron04 but still some prints are not replaced in your PR, e.g. 
https://github.com/isbm/berrymill/pull/41/files#diff-f7a231c65287e1d3c4ad3023ad39303ee5356c17e2f1a8f392813b31a492ed36L18

**Comment by osab270844** [comment]
I'm checking the tests output capture right now.

**Comment by osab270844** [comment]
replaced by https://github.com/isbm/berrymill/pull/45 to rebase the log-fixes branch.

**Pull request closed without merging**
